In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("./dataset/dataset_refined_new.csv")

In [4]:
data

Directors Language  Year of Release  Action  Thriller  SciFi  \
0     S.S. Rajamouli   Telugu             2017       1         0      0   
1     Advait Chandan    Hindi             2017       0         0      0   
2    Ali Abbas Zafar    Hindi             2017       1         1      0   
3       Rohit Shetty    Hindi             2017       1         0      0   
4    Saket Chaudhary    Hindi             2017       0         0      0   
..               ...      ...              ...     ...       ...    ...   
388     Rohit Dhawan    Hindi             2023       1         0      0   
389   V. Harikrishna  Kannada             2023       1         0      0   
390       R. Chandru  Kannada             2023       1         0      0   
391    Venu Yeldandi   Telugu             2023       0         0      0   
392      Vishwak Sen   Telugu             2023       1         0      0   

     Biography  Drama  History  Romance  ...  Crime  Adventure  Horror  Sport  \
0            0      1        0        0  ...      0          0       0      0   
1            0      1        0        0  ...      0          0       0      0   
2            0      0        0        0  ...      0          1       0      0   
3            0      0        0        0  ...      0          0       0      0   
4            0      1        0        0  ...      0          0       0      0   
..         ...    ...      ...      ...  ...    ...        ...     ...    ...   
388          0      1        0        0  ...      0          0       0      0   
389          0      1        0        0  ...      0          0       0      0   
390          0      1        0        0  ...      1          0       0      0   
391          0      1        0        0  ...      0          0       0      0   
392          0      1        0        0  ...      0          0       0      0   

     Fantacy  War  Ratings   Votes  Worldwide Gross in Crores  Hit or Flop  
0          0    0      8.2  105531                     1749.0            1  
1          0    0      7.8   27522                      830.8            1  
2          0    0      5.9   30693                      562.5            1  
3          0    0      4.9    9917                      310.3            1  
4          0    0      7.8   30211                      304.0            1  
..       ...  ...      ...     ...                        ...          ...  
388        0    0      5.3   27155                       51.5            0  
389        0    0      7.4   10092                       45.0            1  
390        0    0      7.7   13421                       41.9            0  
391        0    0      8.3    1627                       25.5            1  
392        0    0      7.0     876                       21.5            1  

[393 rows x 21 columns]

In [5]:
all_directors = {}
dircnt = 0

In [6]:
for i in range(len(data)):
    if data.loc[i]['Directors'] not in all_directors:
        all_directors[data.loc[i]['Directors']] = dircnt
        dircnt += 1

In [7]:
all_directors

{'S.S. Rajamouli': 0,
 'Advait Chandan': 1,
 'Ali Abbas Zafar': 2,
 'Rohit Shetty': 3,
 'Saket Chaudhary': 4,
 'Shree Narayan Singh': 5,
 'Rahul Dholakia': 6,
 'Atlee': 7,
 'Kabir Khan': 8,
 'David Dhawan': 9,
 'Shashank Khaitan': 10,
 'Subhash Kapoor': 11,
 'V.V. Vinayak': 12,
 'Ravi Udyawar': 13,
 'Sanjay Gupta': 14,
 'Imtiaz Ali': 15,
 'K.S. Ravindra': 16,
 'Siva': 17,
 'A.R. Murugadoss': 18,
 'Harish Shankar': 19,
 'Hari': 20,
 'Bharathan': 21,
 'Mohit Suri': 22,
 'Mrighdeep Lamba': 23,
 'Milan Luthria': 24,
 'Kishore Kumar Pardasani': 25,
 'Anees Bazmee': 26,
 'Anurag Basu': 27,
 'Sekhar Kammula': 28,
 'James Erskine': 29,
 'Mohan Raja': 30,
 'Radha Krishna Jagarlamudi': 31,
 'Venu Sriram': 32,
 'Santhosh Ananddram': 33,
 'R.S. Prasanna': 34,
 'Sankalp Reddy': 35,
 'Gayatri': 36,
 'Trinadha Rao Nakkina': 37,
 'Shiva Nirvana': 38,
 'H. Vinoth': 39,
 'Anil Ravipudi': 40,
 'Satish Vegesna': 41,
 'Ashwiny Iyer Tiwari': 42,
 'Soundarya Rajinikanth Vishagan': 43,
 'Shivam Nair': 44,
 'A

In [8]:
all_languages = {}
langcnt = 0

In [9]:
for i in range(len(data)):
    if data.loc[i]['Language'] not in all_languages:
        all_languages[data.loc[i]['Language']] = langcnt
        langcnt += 1

In [10]:
all_languages

{'Telugu': 0,
 'Hindi': 1,
 'Tamil': 2,
 'Kannada': 3,
 'Malayalam': 4,
 'Punjabi': 5}

In [11]:
encoded_directors = {w:k for k,w in all_directors.items()}
encoded_languages = {w:k for k,w in all_languages.items()}

In [12]:
X = data.drop(['Hit or Flop'], axis=1)
y = data['Hit or Flop']

In [13]:
X = np.array(X)
y = np.array(y)

In [14]:
for i in range(len(X)):
    X[i][0] = all_directors[X[i][0]]
    X[i][1] = all_languages[X[i][1]]

In [15]:
X = np.array(X, dtype='int32')
y = np.array(y, dtype='int32')

In [16]:
y = y.ravel()

In [17]:
print(np.unique(y, return_counts=True))

(array([0, 1]), array([142, 251], dtype=int64))


In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [20]:
from sklearn.svm import SVC
model1 = SVC().fit(X_train, y_train)
model1.score(X_test, y_test)

0.625

In [21]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier().fit(X_train, y_train)
model2.score(X_test, y_test)

0.7

In [22]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier(n_estimators=200).fit(X_train, y_train)
model3.score(X_test, y_test)

0.75

In [23]:
print(X[5])

[    5     1  2017     0     0     0     0     1     0     1     1     0
     0     0     0     0     0     7 22202   290]


In [24]:
test = np.array(X[5]).reshape(1, -1)

In [25]:
model1.predict(test)

array([1])

In [26]:
model2.predict(test)

array([1])

In [27]:
model3.predict(test)

array([1])

In [28]:
import pickle as pkl

In [29]:
with open('model.pkl', 'wb') as f:
    pkl.dump(model3, f)

In [30]:
with open('directors.pkl', 'wb') as f:
    pkl.dump(all_directors, f)

In [33]:
with open('languages.pkl', 'wb') as f:
    pkl.dump(all_languages, f)

In [31]:
encoded_directors

{0: 'S.S. Rajamouli',
 1: 'Advait Chandan',
 2: 'Ali Abbas Zafar',
 3: 'Rohit Shetty',
 4: 'Saket Chaudhary',
 5: 'Shree Narayan Singh',
 6: 'Rahul Dholakia',
 7: 'Atlee',
 8: 'Kabir Khan',
 9: 'David Dhawan',
 10: 'Shashank Khaitan',
 11: 'Subhash Kapoor',
 12: 'V.V. Vinayak',
 13: 'Ravi Udyawar',
 14: 'Sanjay Gupta',
 15: 'Imtiaz Ali',
 16: 'K.S. Ravindra',
 17: 'Siva',
 18: 'A.R. Murugadoss',
 19: 'Harish Shankar',
 20: 'Hari',
 21: 'Bharathan',
 22: 'Mohit Suri',
 23: 'Mrighdeep Lamba',
 24: 'Milan Luthria',
 25: 'Kishore Kumar Pardasani',
 26: 'Anees Bazmee',
 27: 'Anurag Basu',
 28: 'Sekhar Kammula',
 29: 'James Erskine',
 30: 'Mohan Raja',
 31: 'Radha Krishna Jagarlamudi',
 32: 'Venu Sriram',
 33: 'Santhosh Ananddram',
 34: 'R.S. Prasanna',
 35: 'Sankalp Reddy',
 36: 'Gayatri',
 37: 'Trinadha Rao Nakkina',
 38: 'Shiva Nirvana',
 39: 'H. Vinoth',
 40: 'Anil Ravipudi',
 41: 'Satish Vegesna',
 42: 'Ashwiny Iyer Tiwari',
 43: 'Soundarya Rajinikanth Vishagan',
 44: 'Shivam Nair',
 45